global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "wss"
    dns_sd_configs:
      - names: ["tasks.wss"]
        type: A
        port: 9000

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']